# Generated by Django 4.2.6 on 2023-10-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=70, verbose_name='Название')),
                ('describe', models.TextField(verbose_name='Краткое описание')),
                ('RAM', models.IntegerField(verbose_name='Объём RAM')),
                ('SSD', models.FloatField(verbose_name='Объем SSD')),
                ('long_describe', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='laptops/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
    ]
